[project]
name = "blobs"
version = "0.1"
dependencies = ["pyglet"]

[project.scripts]
blobs_c = "blobs:main"

[project.gui-scripts]
blobs = "blobs:main"

[tool.pydeploy]
data_dirs = [["data", "data"]]
